AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Lambda, SQS, and S3
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: swapibucket
  MySQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: swapiqueue
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: SWAPIFunction
      Runtime: python3.9
      Timeout: 210
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code:
        S3Bucket: travel1s3bucket
        S3Key: lambda_function.zip
      Environment:
        Variables:
          SQS_QUEUE_URL:
            Fn::GetAtt:
              - MySQSQueue
              - QueueUrl
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: swapicloudstack
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: swapi-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                  - sqs:DeleteMessage
                Resource:
                  Fn::GetAtt:
                    - MySQSQueue
                    - Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  Fn::Join:
                    - ''
                    - - Fn::GetAtt:
                          - MyS3Bucket
                          - Arn
                      - '/*'
Outputs:
  LambdaFunctionName:
    Description: Name of the created Lambda function
    Value:
      Ref: MyLambdaFunction
  SQSQueueURL:
    Description: URL of the created SQS queue
    Value:
      Fn::GetAtt:
        - MySQSQueue
        - QueueUrl
  S3BucketName:
    Description: Name of the created S3 bucket
    Value:
      Ref: MyS3Bucket
