AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for SWAPI Stack

Parameters:
  LambdaFunctionCode:
    Description: SWAPI Stack LambdaFunction Code
    Type: String
    Default: lambda_function.zip

Resources:
  SWAPIBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: swapibucket1

  SWAPIQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: swapiqueue

  StackAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: SWAPI

  SWAPIFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: SWAPIFunction
      Runtime: python3.9
      Timeout: 230
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code:
        S3Bucket: travel1s3bucket
        S3Key: !Ref LambdaFunctionCode
      Environment:
        Variables:
          SQS_QUEUE_URL:
            Fn::GetAtt:
              - SWAPIQueue
              - QueueUrl

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: swapicloudstack
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: swapi-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 'arn:aws:logs:*:*:*'
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:ReceiveMessage
                - sqs:GetQueueAttributes
                - sqs:DeleteMessage
              Resource:
                Fn::GetAtt:
                  - SWAPIQueue
                  - Arn
            - Effect: Allow
              Action: 
                - cloudformation:CreateStack
                - cloudformation:DeleteStack
                - cloudformation:UpdateStack
                - cloudformation:DescribeStacks
                - cloudformation:CreateChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:DeleteChangeSet
                - cloudformation:ExecuteChangeSet
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject  # Added permission to get the S3 object
                - s3:PutObject
                - s3:PutObjectAcl
              Resource:
                Fn::Sub:
                  - arn:aws:s3:::${BucketName}/*
                  - BucketName: !Ref SWAPIBucket
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: arn:aws:lambda:us-east-1:876332050529:function/SWAPI_Function
  
  MyApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref StackAPI
      ParentId: !GetAtt 
        - StackAPI
        - RootResourceId
      PathPart: films
  
  MyApiMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      ApiKeyRequired: False
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId:
        Fn::GetAtt:
          - MyApiResource
          - ResourceId
      RestApiId:
        Ref: StackAPI
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SWAPIFunction.Arn}/invocations

  LambdaApiGatewayPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SWAPIFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/*/*"

Outputs:
  SWAPIFunction:
    Description: SWAPIFunction Lambda Code
    Value:
      Ref: SWAPIFunction

  SWAPIQueue:
    Description: SWAPI SQS Queue
    Value:
      Fn::GetAtt:
        - SWAPIQueue
        - QueueUrl

  SWAPI_S3_Bucket:
    Description: SWAPI S3 Bucket
    Value:
      Ref: SWAPIBucket

  LambdaFunctionCode:
    Description: LambdaFunctionCode Object Key
    Value: !Ref LambdaFunctionCode
 
  ApiGatewayEndpoint:
    Description: API Gateway Endpoint
    Value:
      Fn::Sub: "https://${StackAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/films"