name: SWAPI-Stack Deploy

on:
  push:
    branches:
      - main 
      
jobs:
  deploy_code:
      runs-on: ubuntu-latest
      permissions:
            id-token: write
            contents: read
      env:
        working-directory : ./src
            
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2.3.5
  
        - name: Configure AWS 
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
            aws-region: us-east-1 
                  
        - name: Fetch Lambda Function Code
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              src

        - name: Zip Archive
          run: zip -r -j lambda_function.zip src/lambda_function.py
  
        - name: Upload to S3
          run: |
            aws s3 cp lambda_function.zip s3://swapibucket1/
            
  deploy_infra:
      runs-on: ubuntu-latest
      needs: deploy_code
      permissions:
            id-token: write
            contents: read
      env:
        working-directory : ./aws
            
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2.3.5
  
        - name: Configure AWS 
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
            aws-region: us-east-1 
            
        - name: Deploy to AWS CloudFormation
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: SWAPI-Stack
            template: aws/CFLambdaTemplate.yaml
            capabilities: CAPABILITY_NAMED_IAM
          
